# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd7b41781a4bd2903a7c351231cd2adfecb7d1fdf710c069697d06b20ddc25f944bad13c1d85ce4279fb898ea2888c7d660328ce1d771e4776fdc1f2efc6fade

test:
  secret_key_base: 2acb9f8bf48423371c38c6f59238c6ec65d05bad116a50e1ba06bf039277a30ab32d7bb0bab1918d13963b95427670e14ef0f465a3e4d78ea2b716239705b930

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
